"use strict";
function assert ( mustBeTrue , message ) { if ( mustBeTrue === true ) { return ; } ; throw new Test262Error ( message ) ; } if ( 0 ) ; else ; switch ( 0 ) { } assert . notSameValue = async x => 0 ; assert . throws = function ( expectedErrorConstructor , func , message ) { var expectedName , actualName ; if ( typeof func !== "function" ) { debugger ; return ; } if ( message === undefined ) { message = '' ; } else { message += ' ' ; } try { func ( ) ; } catch ( thrown ) { if ( typeof thrown !== 'object' || thrown === null ) { message += 'Thrown value was not an object!' ; throw new Test262Error ( message ) ; } else if ( 0 ) ; return ; } ; throw new Test262Error ( message ) ; } ; assert . _toString = { groups : true } ; function Test262Error ( message ) { this . message = message || "" ; } Test262Error . prototype . toString = function ( ) { return "Test262Error: " + this . message ; } ; Test262Error . thrower = ( message ) => { throw new Test262Error ( message ) ; } ; class x { } var accessed = false ; function callbackfn ( val , idx , obj ) { if ( idx > 0 ) { accessed = true ; } if ( idx === 0 ) { throw new Error ( "Exception occurred in callbackfn" ) ; } return false ; } var obj = { 0 : 9 , 1 : 100 , 10 : 11 , length : 20 } ; assert . throws ( Error , function ( ) { Array . prototype . some . call ( obj , callbackfn ) ; } ) ; assert . sameValue ( accessed , false , 'accessed' ) ; 
